### ISSUE TITLE
Neuer Pull- und Buildversuch

### ISSUE THREAD

**Issue by Nedomil** [Nedomil/sokoban#1]
**Frage**
@Woodsworth: Ich habe eben versucht, die Meshs hochzuladen. Kannst du testen, ob du das Projekt jetzt builden kannst? (Musst es zuerst pullen via `git pull`.

**Comment by Woodsworth** [comment]
@Nedomil 
Ich habe gepullt, jedoch scheinen die Meshes immer noch zu fehlen:

> G:\Projekte\Sokoban\sokoban>git pull
> Merge made by the 'recursive' strategy.
>  .gitignore                                         |   4 --
>  Sokoban/Assets/Scripts/Driver.cs                   |   9 ++-
>  Sokoban/Assets/Scripts/GUI/ButtonManager.cs        |  74 ++++++++-------------
>  Sokoban/Assets/Scripts/GUI/Interfaces/IGUIHide.cs  |   2 +-
>  Sokoban/Assets/Scripts/GUI/LandButton.cs           |  53 ++++++++++++++-
>  Sokoban/Assets/Scripts/GUI/LeaveButton.cs          |  22 +++++-
>  Sokoban/Assets/Scripts/GUI/RestartButton.cs        |  22 +++++-
>  Sokoban/Assets/Scripts/Sokoban.cs                  |   8 ++-
>  Sokoban/Assets/Scripts/SpaceObjects/SpacePlayer.cs |   2 +-
>  Sokoban/Library/**CurrentLayout.dwlt**                 | Bin 46228 -> 46268 bytes
>  Sokoban/Library/**InspectorExpandedItems.asset**       | Bin 4340 -> 4340 bytes
>  .../ScriptAssemblies/Assembly-CSharp.dll.mdb       | Bin 16860 -> 17175 bytes
>  Sokoban/Library/assetDatabase3                     | Bin 3026008 -> 3026008 bytes
>  Sokoban/Library/**expandedItems**                      | Bin 4200 -> 4188 bytes
>  .../metadata/16/164f243bce350a1439274c32b9694e8d   | Bin 6705 -> 6405 bytes
>  .../16/164f243bce350a1439274c32b9694e8d.info       | Bin 609 -> 634 bytes
>  .../metadata/28/28060fef97e85014191fabe8e67bfaf9   | Bin 4665 -> 4677 bytes
>  .../28/28060fef97e85014191fabe8e67bfaf9.info       | Bin 605 -> 630 bytes
>  .../metadata/41/41a0f115fbf5d824d82b298d61815293   | Bin 5761 -> 6229 bytes
>  .../41/41a0f115fbf5d824d82b298d61815293.info       | Bin 603 -> 628 bytes
>  .../metadata/b7/b7dd79b302fb8e74ab19822b2858cc65   | Bin 7101 -> 7277 bytes
>  .../b7/b7dd79b302fb8e74ab19822b2858cc65.info       | Bin 584 -> 609 bytes
>  .../metadata/c4/c44e566c76761dd4f92fa93dc9238810   | Bin 7081 -> 7193 bytes
>  .../c4/c44e566c76761dd4f92fa93dc9238810.info       | Bin 587 -> 612 bytes
>  .../metadata/d3/d37195aa1c0cf5342a1a8fdc5d691cbc   | Bin 5437 -> 5909 bytes
>  .../d3/d37195aa1c0cf5342a1a8fdc5d691cbc.info       | Bin 609 -> 634 bytes
>  .../metadata/f5/f5cb43c56193eae488079bb6283f8b03   | Bin 9829 -> 9853 bytes
>  .../f5/f5cb43c56193eae488079bb6283f8b03.info       | Bin 612 -> 637 bytes
>  .../metadata/f8/f8f9281c3b821d145a4fd419cdd9023d   | Bin 6221 -> 7745 bytes
>  .../f8/f8f9281c3b821d145a4fd419cdd9023d.info       | Bin 600 -> 625 bytes
>  **30 files changed, 132 insertions(+), 64 deletions(-)**

Zudem vermute ich, dass wir die **markierten** Ordner ignorieren können.
