### ISSUE TITLE
Mine befindet sich im Boden

### ISSUE THREAD

**Issue by Nedomil** [Nedomil/sokoban#4]
**Problemstellung**
Die Mine befindet sich im Boden. 

**Lösungsansatz**
Hat einen anderen Mittelpunkt als die anderen Objekte.

**Bildmaterial**
![image](https://cloud.githubusercontent.com/assets/22456707/21280136/72d674a2-c3e4-11e6-9a0c-03773fccbb0f.png)

**Comment by Woodsworth** [comment]
Da alle Models nochmal überarbeitet wurden, ist das Problem mit der Bombe jetzt auch behoben.
